# -*- coding: utf-8 -*-
"""Python_Basics_task1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z7Ujy_x-qRY6zoA1OBl-F1RP-nVD9kjs
"""



"""## **1- Write a Python program to find the area of a triangle**"""

length = float(input())
width = float(input())
# area of a triangle = length*width
area = length * width
print("the area of a triangle = ", area)

"""# **2- Write a Python program to swap two variables.**

"""

num1 =38
num2 =92
swap = num1
num1 = num2
num2=swap
print(f'the val. of num1 = {num1}')
print(f'the val. of num1 = {num2}')

"""# **3-Write a Python program to enter a number from user and convert this number from kilometers to miles.**

"""

Distance_kilometers = float(input())
#Distance in miles = Distance in kilometers × 0.621371
Distance_miles = Distance_kilometers * 0.621371

print("Distance in miles = ",Distance_miles )